# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "regional-valuation-app"
client_id = "eef555c78593a1123549c43bf6b8775e"
application_url = "https://available-adam-ease-increasing.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://available-adam-ease-increasing.trycloudflare.com/auth/callback",
  "https://available-adam-ease-increasing.trycloudflare.com/auth/shopify/callback",
  "https://available-adam-ease-increasing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-359a18b0.myshopify.com"
